In [1]:
from scipy.stats import t
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt 

In [ ]:
#simulation 1

In [121]:
np.random.seed(1)
x1 = np.random.standard_t(3,150)
y1 = np.random.standard_t(3,150)+0.5

In [122]:
print(x1)
print('\n \n')
print(y1)

[ 2.52088116 -1.13756823 -1.09478858 ...  1.2421455   1.16226079
 -1.21555235]

 

[0.59030596 0.46567641 0.34515782 ... 0.85678076 0.72924787 2.13084292]


In [123]:
pd.set_option('display.max_rows', 500)

In [124]:
ds1 = pd.DataFrame()
ds2 = pd.DataFrame()
n1 = np.repeat(0, 150)
n2 = np.repeat(1, 150)

In [125]:
ds1['X'] = x1.tolist()
ds1['Y'] = n1.tolist()
ds2['X'] = x1.tolist()
ds2['Y'] = n2.tolist()
ddd = [ds1,ds2]
ds = pd.concat(ddd).reset_index().drop(columns='index')

In [126]:
ds

X  Y
0      2.520881  0
1     -1.137568  0
2     -1.094789  0
3     -1.707813  0
4      0.407928  0
...         ... ..
39995  1.727772  1
39996  0.616897  1
39997  1.242145  1
39998  1.162261  1
39999 -1.215552  1

[40000 rows x 2 columns]

In [127]:
x = ds.iloc[:,:-1].values
y = ds.iloc[:,-1].values

In [128]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, shuffle=True)

In [129]:
print(y_train)
print(y_test)

[0 1 1 ... 0 0 0]
[1 1 1 ... 1 1 0]


In [130]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric = 'euclidean', p = 5)
knn.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', p=5)

In [131]:
y_pred = knn.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 ...
 [0 1]
 [0 1]
 [1 0]]


In [132]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 885 3114]
 [3174  827]]


0.214

In [133]:
#svc

In [134]:
from sklearn.svm import SVC
sprt = SVC(kernel = 'linear', random_state  = 0)
sprt.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [135]:
y_pred = sprt.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [0 1]
 [0 0]]


In [136]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1294 2705]
 [1316 2685]]


0.497375

In [138]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [139]:
y_pred4 = nb.predict(x_test)
print(np.concatenate((y_pred4.reshape(len(y_pred4),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [0 0]]


In [140]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred4)
print(cm)
accuracy_score(y_test, y_pred4)

[[ 913 3086]
 [ 871 3130]]


0.505375

In [137]:
results = pd.DataFrame({
    'size': [100,300,1000,2000,20000],
    'knn': [0.1,0.183,0.235,0.19,0.214],
    'svm': [0.45,0.45,0.455,0.4925,0.49737]})


results

size    knn      svm
0    100  0.100  0.45000
1    300  0.183  0.45000
2   1000  0.235  0.45500
3   2000  0.190  0.49250
4  20000  0.214  0.49737